info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}
      
spring:
  data:
    mongodb:
     host: localhost
     port: 27017
     database: scheduling-job